M48
; DRILL file {KiCad 9.0.8} date 2026-04-15T02:58:34+1000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-15T02:58:34+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.8
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.500
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.700
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T3C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.800
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T5C1.500
%
G90
G05
T1
X104.3Y-69.929
X104.3Y-71.829
T2
X109.136Y-79.552
X110.339Y-80.832
T3
X97.312Y-74.346
X104.5Y-75.5
T4
X97.3Y-68.979
X97.3Y-72.779
T5
X92.5Y-79.5
X92.5Y-94.5
M30
